<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-EUNNNQG0" name="org.example.testRunner.runners" tests="20" failures="2" timestamp="2022-08-13T13:29:49 EET" time="257.028" errors="1">
  <testcase name="runScenario" time="7.115" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="7.327" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="22.978" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.401" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="13.046" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="10.603" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="19.598" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.352" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="8.355" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.935" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.792" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.827" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.986" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="6.924" classname="org.example.testRunner.runners">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.stepDefs.D06_homeSlidersStepDef.check_nokia_url(D06_homeSlidersStepDef.java:22)
at ✽.check if url is nokia url(file:///C:/Users/Mahfouz%20Sherif/IdeaProjects/FinalProject/src/main/resources/features/F06_homeSliders.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="7.572" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="57.601" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.929" classname="org.example.testRunner.runners">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.stepDefs.D06_homeSlidersStepDef.check_iphone_url(D06_homeSlidersStepDef.java:33)
at ✽.check if url is iphone url(file:///C:/Users/Mahfouz%20Sherif/IdeaProjects/FinalProject/src/main/resources/features/F06_homeSliders.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="9.306" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.116" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.265" classname="org.example.testRunner.runners">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.example.stepDefs.D07_followUsStepDef.check_link(D07_followUsStepDef.java:37)
at ✽."https://demo.nopcommerce.com/new-online-store-is-open" is opened in new tab(file:///C:/Users/Mahfouz%20Sherif/IdeaProjects/FinalProject/src/main/resources/features/F07_followUs.feature:15)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- org.example.testRunner.runners -->
